### ISSUE TITLE
Can't not minifiy files for old versions

### ISSUE THREAD

**Issue by pvnr0082t** [Flyer53/jsPanel3#21]
Hi @Flyer53 ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs), we want to host this library.
I fetch some old versions like `3.0.0-rc1.9`, `3.0.0-rc1.10`, there is no minified files under `source` folder. I try to minify myself but got some error:

```
Parse error at jquery.jspanel.js:137,14
Unexpected character '`'
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at parse_error (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1647:9)
    at Object.next_token [as input] (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1912:9)
    at next (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2012:25)
    at expect_token (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2045:20)
    at expect (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2050:36)
    at eval (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2610:13)
    at eval (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2073:24)
    at expr_atom (eval at <anonymous> (/home/p/web-minify-helper/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2540:35)
```

The minify tool comes from https://github.com/PeterDaveHello/web-minify-helper. I'd like to know if it's possible to provide official minified filed for old versions or provide the tool you use. Thank you.

https://github.com/cdnjs/cdnjs/issues/8624

**Comment by Flyer53** [comment]
Hey there,
thanks a lot for your plans to host jsPanel under cdnjs. I appreciate this very much.
I prepared a zip file that includes all jsPanel version 3.x releases with also minified js and css files. Download it from http://jspanel.de/downloads/jsPanel3-all-releases.zip
I hope this is ok with you and solves this issue. If not don't hesitate to write again.

Regards, Stefan

**Comment by pvnr0082t** [comment]
Thanks for your big help. I think it will be very helpful. :+1:

**Comment by Flyer53** [comment]
My pleasure :)
If there is anything else I can do .... just tell me.

**Comment by Flyer53** [comment]
jsPanel3 is now available on cdnjs https://cdnjs.com/libraries/jspanel3
